apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: skais-gateway
  namespace: skais-2-test
spec:
  # Demo Only !!
  selector:
    istio: gateway
  servers:
    - port:
        number: 8080
        name: http
        protocol: HTTP
      hosts:
        - "*"
