apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-skais-2-test.yaml
  - service-account-service-a.yaml
  - service-account-service-b.yaml
  - service-a-svc.yaml
  - service-b-svc.yaml
  - deployment-service-a.yaml
  - deployment-service-b.yaml