apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: strict-mtls-service-a
  namespace: skais-2-test
spec:
  selector:
    matchLabels:
      app: label-service-a
      # from here:
      # Deployment.spec.template.metadata.labels.app --> "label-service-a"
  mtls:
    mode: STRICT