apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: my-ingress-nginx

labels:
  - pairs:
      environment: skais-test
      created-for: istio
    includeSelectors: false # not break selectors
    includeTemplates: true # apply to pods

resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml
